### ISSUE TITLE
出现多个报错，QQ中不返回图片，沙盒返回一个图片占位符

### ISSUE THREAD

**Issue by himetuki** [Alin-sky/koishi-plugin-ba-koharutalk#2]
![image](https://github.com/Alin-sky/koishi-plugin-ba-koharutalk/assets/94748099/72169c38-a95a-402a-96aa-a000ba745038)
![image](https://github.com/Alin-sky/koishi-plugin-ba-koharutalk/assets/94748099/5ea93370-726d-41b3-b68a-7b54be446af7)
![image](https://github.com/Alin-sky/koishi-plugin-ba-koharutalk/assets/94748099/d7459ce8-559f-46ff-b15b-3e94368142c1)
![image](https://github.com/Alin-sky/koishi-plugin-ba-koharutalk/assets/94748099/7e076a57-bcc1-488d-944e-bab2b6e7192b)

**Comment by Alin-sky** [comment]
好像是配置项没有选择分辨率，目前版本还有问题，之后会修复呜呜呜

**Comment by himetuki** [comment]
大丈夫大丈夫
![df0128b208d29b6d2058f4877e313224](https://github.com/Alin-sky/koishi-plugin-ba-koharutalk/assets/94748099/7ebbeeb5-38ae-4502-95f0-a1353821fe5e)
